#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py clear_cache

exec uvicorn config.asgi:application --host 0.0.0.0 --workers 2 --timeout-graceful-shutdown 0